### ISSUE TITLE
Sender does not send "detach" and "close" frame before ends

### ISSUE THREAD

**Issue by rkubis** [rh-messaging/cli-rhea#14]
**Step to reproduce:**
`cli-rhea-sender  --broker <IP>:5672 --log-msgs interop --count 1 --log-lib TRANSPORT_FRM --address examples`

**There is not detach and close frame.**

**Comment by jdanekrh** [comment]
Probably caused by the `process.exit(0);` Removing it fixes the problem for me (but probably breaks whatever the exit was added for).

**Comment by kornys** [comment]
@jdanekrh yep I was caused by process.exit(0), I used that for temporary fix one issue which we had in enamsse tests with rhea, I have to change handling of exit from client.
