### ISSUE TITLE
Default message priority should be 4, not None/undefined

### ISSUE THREAD

**Issue by rkubis** [rh-messaging/cli-rhea#16]
**Step to reproduce:**
`cli-rhea-sender -b <IP>:5672 -a examples -c 1 --log-msgs interop`

**Now is priority printed as None:**
{"durable":False,"priority":**None**,"ttl":None,"first-acquirer":None,"delivery-count":0,"id":None,"user-id":None,"address":"examples","subject":None,"reply-to":None,"correlation-id":None,"content-type":"string","content-encoding":None,"absolute-expiry-time":None,"creation-time":None,"group-id":None,"group-sequence":None,"reply-to-group-id":None,"properties":None,"content":None}

**Should be 4:**
{"durable":False,"priority":**4**,"ttl":None,"first-acquirer":None,"delivery-count":0,"id":None,"user-id":None,"address":"examples","subject":None,"reply-to":None,"correlation-id":None,"content-type":"string","content-encoding":None,"absolute-expiry-time":None,"creation-time":None,"group-id":None,"group-sequence":None,"reply-to-group-id":None,"properties":None,"content":None}

**Comment by jdanekrh** [comment]
That's not what I am seeing. I see `"priority": 0` in the output. Which is also not correct.

**Comment by kornys** [comment]
@jdanekrh so rhea lib has no object Message exposed to using, if you send message you fill data which you want and rest is filled by default values in send method. So my formatter format data which is set by user via commands and if you don't specify for example message priority, I (as developer of cli-rhea), have no chance to get default values of message properties, header etc... So this issue has no pretty solution. I only can set priority and rest of parameters in options parser to default amqp 1.0 values.

**Comment by rkubis** [comment]
@jdanekrh There is not any class/object for message, so message is printed only with user-defined values. The rest of (default) values is set in _send_ method and it is not possible to get whole sent message. Do we want feature to get whole message before send?

**Comment by jdanekrh** [comment]
Aha, thanks for explaining the problem. I am not sure, TBH. Probably not. We could fake it in test, instead.

    if sent_message['priority'] is None:
        sent_message['priority'] = 4

This is imo perfectly ok to do in a sent message.

Thinking this way, we may as well put the if None then 4 into cli-rhea. (Only for sender, of course.)

**Comment by rkubis** [comment]
Fixed in fa9b11ae737735d771c290268ba369d7076f272d
